# Versões dos pacotes
FIRACODE_VERSION="5.2"
FERDIUM_VERSION="6.7.6"
EMBY_VERSION="4.8.8.0"
PLEX_VERSION="1.40.4.8679"
HYPERKEYS_VERSION="1.3.0"
NVM_VERSION="0.40.1"

# Git credentials (fallback para prompt)
emailgit="user@example.com"
usergit="User"
